### ISSUE TITLE
don’t use var

### ISSUE THREAD

**Issue by flying-sheep** [eventualbuddha/add-variable-declarations#1]
`var` is all but deprecated.

immutable variables should use `const` and variable ones `let`.

**Comment by eventualbuddha** [comment]
I do prefer not to use `var`. However, it's not trivial to do the analysis to determine whether something can be (a) block scoped and (b) `const`. That's why I wrote that as a plugin to esnext that can be used in combination with this library like so:

```js
import addVars from 'add-variable-declarations';
import { convert } from 'esnext';

let source = `
a = 1;
b = 2;
b++;
`;

console.log(convert(addVars(source).code).code);
// const a = 1;
// let b = 2;
// b++;
```
